[package]
name = "mobc-reql"
version = "0.1.0"
authors = ["rushmorem <rushmore@webenchanter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-lite = "1.11.3"
mobc = "0.7.2"
reql = "0.2.0"

[dev-dependencies]
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread", "sync"] }
