[package]
name = "reql"
description = "A native ReQL driver"
version = "0.1.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/rethinkdb/rethinkdb-rs"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "rethinkdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]
edition = "2018"

[dependencies]
async-stream = "0.3.0"
dashmap = "4.0.2"
futures = "0.3.14"
log = "0.4.14"
ql2 = "2.1.0"
scram = "0.6.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
env_logger = "0.8.3"
reql-types = "0.0.4"
