[package]
name = "reql-examples"
version = "0.1.0"
authors = ["rushmorem <rushmore@webenchanter.com>"]
edition = "2018"
publish = false

[dependencies]
env_logger = "0.8.3"
futures = "0.3.14"
mobc = "0.7.2"
mobc-reql = "0.2.0"
reql = "0.4.0"
reql-types = "0.0.4"
serde_json = "1.0.64"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread", "sync"] }

[[example]]
name = "minimal"
path = "reql/minimal.rs"

[[example]]
name = "changes"
path = "reql/changes.rs"

[[example]]
name = "simple"
path = "mobc/simple.rs"
